linuxmint/xviewer

- src/xviewer-print-preview.c
see https://github.com/mate-desktop/eom/commit/b7849cc5b6e7fd741ef04e334f586266a444ef8a
> avoid integer overflow when allocating a large block of memory

- src/xviewer-window.c
This results in some extremely annoying behvior. Things like clicking the
toolbar navigation arrows will trigger an unintentional fullscreen/unfullscreen.
Instead limit this behavior to only working when double clicking on the actual
image in the view.
Closes: https://github.com/linuxmint/xviewer/issues/26
> ui: Don't handle double click events globally for the window

- src/xviewer-window.c
We don't do this in the other xapps and I'm not sure why we would want this
behavior here.
> window: Don't hide the sidebar when going fullscreen

- data/xviewer-toolbar.xml
- data/xviewer-ui.xml
- src/xviewer-window.c
Previously: "In" was left, "Out" was right,
now: "Out" is left, "In" is right.
It's the same UI change as in https://github.com/linuxmint/xreader/pull/131
> Switch zoom buttons in toolbar

- src/xviewer-window.c
Set a proper icon based on weather or not the slideshow is currently playing or
paused. Also make sure the button actually shows the active state when it's
playing.
Fixes: https://github.com/linuxmint/xviewer/issues/38
> fullscreen-toolbar: Fix the slideshow play/pause button icon

- src/xviewer-thumbnail.c
- src/xviewer-thumbnail.h
gnome_desktop_thumbnail has been removed in gnome-desktop-3.28
Based on https://github.com/GNOME/eog/commit/0e7749ba0bfac7e72c19841afcbebb10851533b4
> Fix build with gnome-desktop-3.28 development

- po/en_CA.po
This patch corrects the Date/Time metadata properties panel. It currently displays a%, 29 December Y%.
This occurs when the locale is set to en_CA.
> Corrected strftime-formatted string.

- help/C/shortcuts.page
- src/xviewer-scroll-view.c
Fix registration problem when the '1' key is pressed towards the edge of zoomed to fit image that doesn't reach the edge of the window. This is described in more detail in issue #84.
Also causes the '1' key to toggle between 1:1 and zoomed to fit - useful when wanting to check the focus at different parts of the image - can use one finger to press the '1' key and the other hand to move the mouse. Much easier than having to press '1' and 'F' alternately. Again see issue 84 for details.
(Attempt 2)
> Key1 behaviour changes

- src/xviewer-image.c
Whilst looking at issue #94 I spotted a minor problem if "Edit/Preferences/Automatic orientation" is not checked. In this situation the image that was posted as an example in issue #94 displays still in landscape mode, as expected, but the size shown in the status bar at the bottom of the screen shows the dimensions as if the image had been rotated as defined by the EXIF orientation tags (the tags for both thumbnail and main image are set to 6 to rotate the image 90 deg clockwise).
The fix is to check the autorotate flag before swapping the dimensions.
(Note that this change does not fix issue #94. I can't reproduce the reported error.
> Non auto rotate error

- src/xviewer-window.c
Hey, I noticed a common feature in most image viewers, is they have buttons on the toolbar to quickly view the image in Fullscreen mode or run the Slideshow.
The functionality for Fullscreen and Slideshow was already there but accessible only through the Menu.
This quick change aims to mirror the existing functionalities to the toolbar buttons for Fullscreen and Slideshow.
Screenshot attached -
> Add "View Fullscreen" and "View Slideshow" buttons to toolbar

- data/org.x.viewer.gschema.xml.in
- data/xviewer-preferences-dialog.ui
- src/xviewer-config-keys.h
- src/xviewer-preferences-dialog.c
- src/xviewer-scroll-view.c
These changes address issues #17 and #59 by adding the feature requested in issue #17 and making the mouse scroll and tilt configurable.
Whilst the existing version of xviewer did allow the user to pan the image using scroll in conjunction with Shift and Ctrl this was not obvious without looking at the program code.
The new code adds a tab to the user preferences dialog that allows the user to select the actions for:
Scroll, Scroll + Shift, Scroll + Ctrl, Scroll + Shift + Ctrl
Tilt, Tilt + Shift, Tilt + Ctrl, Tilt + Shift + Ctrl
The actions that can be assigned to the 8 key combinations listed above are:
Zoom
Vertical pan
Horizontal pan
Move to next/previous image
Rotate 90 degrees
No action
("No action" has been included to cover the situation where a user is habituated to use a …
> Configure Mouse Wheel

- src/xviewer-window.c
This PR fixes an error introduced by PR #95 and reported in issue #106. The error causes a non-maximized image window to be centered in the screen when moving to the next or previous image. This mod leaves the window size and position unaltered.
> Stop Centering Window

- src/xviewer-window.c
This PR addresses issue #99. It sets the focus on the "Delete" button rather than leaving the focus on the option of not asking again.
> Delete Dialog Focus

- src/xviewer-scroll-view.c
This change addresses issue #118 where jpgs with dimensions over 16384 pixels don't display right-hand and bottom portions for pixels 16384 upwards correctly. TIF files worked correctly - not sure why.
The problem occurs in xviewer-scroll-view.c/create_surface_from_pixbuf()
Adding the following to the end of the function created a file that, when displayed, showed transparent pixels for those to the right of pixel 16383.
cairo_surface_write_to_png (surface, "test.png");
pix displayed these files correctly so initially I replace the code of the problem function with code from pix. This fixed the problem but the code was more more extensive.
The solution was to change the creation of the surface from:
`	surface = gdk_window_create_similar_surface (gtk_widget_get_window …
> JPG over 16384 pixels

- src/xviewer-image.c
This may be a problem caused by other programs but GIMP (version 2.10.22 and probably all versions since the option of saving colour space information was added) saves BMP files with a BITMAPV5HEADER when the colour space information is to be included. It sets the bV5Compression  member to BI_BITFIELDS (3) for all six variants of BMPs that it saves. This indicates that there is no compression of the data and that the header members bV5RedMask, bV5GreenMask and bV5BlueMask hold the bit masks for the three colours.
The problem is that the Microsoft specification for BITMAPV5HEADER says that BI_BITFIELDS is only valid for 16 and 32-bit files (quite why is questionable) and GIMP sets the mask members correctly but technically the setting of the compression    field is illegal and causes …
> BMP 24-bit Fix

- data/org.x.viewer.gschema.xml.in
- data/xviewer-preferences-dialog.ui
- src/xviewer-config-keys.h
- src/xviewer-preferences-dialog.c
- src/xviewer-window.c
These changes address issue #16. They add an option to the Preferences Slideshow tab to cause the spacebar to pause/resume a slideshow (instead of moving to the next image). By default the option is disabled thereby preserving the current behaviour.
The right-arrow and PgDn keys still function as before to allow the user to move to the next image.
When a slideshow is not active the spacebar still behaves as it has up to now.
> Spacebar Optionally Pauses Slideshow (Fixes: https://github.com/linuxmint/xviewer/issues/16)

- src/xviewer-image.c
PR #123 to open files that had the wrong extensions caused xviewer to stop opening .svgz files.
PR #123 changed the order of determining the file type to be:
1 Check the 'magic numbers'
2 If not determined by the 'magic numbers' method call g_content_type_guess() to try to determine the file type from its contents
3 If the file type isn't determined by steps 1 and 2 call g_file_info_get_content_type() to determine the type from the extension
The problem for .svgz files is that step 2 recognizes the file mime type as application/gzip. As the file type has been recognised step 3 (which would return image/svg+xml-compressed) is omitted.
The change is to call g_file_info_get_content_type() whether or not steps 1 and 2 have identified the file type. Then if step 2 recognized the type as …
> Open svgz files (Fixes: https://github.com/linuxmint/xviewer/issues/128)

- help/C/shortcuts.page
This is a trivial change to swap the order of two of the keys listed in the "Viewing images" section of the shortcut key help.
The lines  "Toggle between 1:1 and best fit" (key 1) has been swapped with "Scroll around a large image"
This means that "Toggle between 1:1 and best fit" now appears immediately below "Actual size (1:1)" and "Best fit" so that the three related keys are grouped together (a change suggested by the poster of issue #150)
> Change to shortcut key help

- src/xviewer-scroll-view.c
This PR fixes the problem reported in issue #24 on 13.9.2021 (I believe the original problem reported in this issue is no longer a problem)
The image uploaded by rmast would only display correctly if xviewer started un-maximized - but even then any attempt to zoom the image resulted (for me) in just a plain white image. Similar to what rmast reported.
The solution appears to be to use CAIRO_FILTER_GOOD instead of CAIRO_FILTER_BILINEAR in function xviewer-scroll-view.c/display_draw(). This not only appears to resolve the issue but also appears to run faster (contrary to the previous comment in that section of the source  code). I zoomed down to 2% and timed how long I had to press the + key to reach 2000% zoom. I also timed the reverse process by holding the - key.  I did this for the file …
> [Next] Fix issue 24

- src/xviewer-list-store.c
This PR addresses issue #151 
It would appear to be intention that xviewer when the file that is currently being displayed is changed by an external program the display should update to reflect the changes. The update should happen without prompting the user unless the image has been altered within xviewer (for example flipped horizontally).
This display is updated automatically (with or without prompting as noted above) in the following situations:
In nemo right-click on the directory that contains the image and select "Open With/Other Application.../Image Viewer". In this case all of the images in that folder will "in-view" update if they are changed externally.
In nemo right-click on an image file and select "Open With/Other Application.../Image Viewer"
In a terminal window opened in …
> Reflect External Changes - Fixes Issue 151

- debian/gir1.2-xviewer-3.0.install
- debian/xviewer-dev.install
- debian/xviewer.install
- src/meson.build
- src/xviewer-plugin-engine.c
Currently the file `Xviewer-3.0.typelib` is located in `$libdir/girepository-1.0`,
i.e. `/usr/lib/x86_64-linux-gnu/girepository-1.0/`.
Therefore, it only works as long as the install $prefix is `/usr` but fails for e.g. `/usr/local`
with `Error loading Xviewer typelib: Typelib file for namespace 'Xviewer', version '3.0' not found`
as this path is not in the default g_ir search path.
This commit changes the path to the xviewer pkglibdir, e.g. `/usr/local/lib/x86_64-linux-gnu/xviewer/girepository-1.0/`
and changes the code to load it from there.
This behavior is similar to Xed's.
Also, the path of the .gir file is moved into the private data dir for consistency.
> fix: move .typelib and .gir dirs into private dir

- src/xviewer-window.c
The current release version (3.2.4) doesn't handle moving to the next or previous images by holding down the appropriate keys - the display just freezes until the key is released.
This pull request sinks any repeated key press events for the next and prev keys until at least 250 milliseconds have passed or the key has been released. This moves from image to image at a rate that allows the user to search for a particular image.
In order to allow rapid press/release cycles of the next and prev keys to work (as they do in the current master version) it was necessary to handle key release events. The existing key press event handler is now called when there is a release event. It handles release events by setting an invalid code into the record of the last key pressed, so that a next/prev key …
> Handle repeated prev and next keys (fixes issue 160)

- src/xviewer-image-jpeg.c
- src/xviewer-image.c
This PR addresses issue #168 
The problem occurs when the following conditions are met:
1. The image has EXIF data containing the orientation tag (0x112)
2. The orientation tag for the image has a value other than 1 when xviewer reads the image
3. Since xviewer made the change the user has scrolled to another image (just scrolling back to this image doesn't fix the problem)
4. The image is saved - either explicitly or as a result of selecting Save when prompted when exiting xviewer
When xviewer rotates or flips an image it does so by actually modifying the image data, rather than (for files that have EXIF data) simply altering the setting of the tag EXIF_TAG_ORIENTATION (0x0112). As a result it has to set the orientation tag to a value of 1 (TopLeft) - it also updates the tags …
> Fix Batch Save - issue #168

- src/xviewer-window.c
The information about Mint 21.0 includes the following news for Xviewer:
"Continuously pressing the arrow keys results in a smooth slideshow where enough time is given for each picture to be visible."
This change was as the result of PR #164 (as a fix for issue #160). It restricted repeating key presses so that they occurred at around 250 milliseconds.
Unfortunately when submitting this PR I failed to realise just how long it can take Mint to load and then display images.
I was holding down the right-arrow key to scroll through a folder of images from a Nikon D3200. These were from about 7.5 to 15 MBytes (all 24 MPixels) - most of the time the images were shown correctly but there were glitches.
I then used a test tif image that is 9486 x 14703 pixels with a file size of 418.4 MBytes. The …
> Handle repeated prev/next keys (take 2)

- src/xviewer-window.c
Use upper case names for boolean constants (False -> FALSE, True -> TRUE). Not all distros support not-upper case variant
> Use upper case names for boolean constants

- src/xviewer-image.c
This is a port of a patch for the same bug in EOG.
`xviewer_image_iter_advance` can return false when the animation has looped a set number of times and should stop playing. Currently, if this function returns false, xviewer will get stuck in an infinite loop.
This also fixes interpreting the return value of `gdk_pixbuf_animation_iter_get_delay_time` as if it were an unsigned integer. According to the [documentation](https://docs.gtk.org/gdk-pixbuf/method.PixbufAnimationIter.get_delay_time.html), it returns -1 when the animation should stop playing, which right now just triggers a very very long timeout.
This is a very simple, single-line fix, so it shouldn't be too much work to review.
> Fix potential infinite while loop and interpreting unsigned int as signed.
